### ISSUE TITLE
[BugReport] output directory generation not working as expected.

### ISSUE THREAD

**Issue by krishna-parajuli** [moest-np/center-randomize#39]
https://github.com/moest-np/center-randomize/blob/607f3db84e5e589f49cf8c9cb165dfa24c0e0b32/school_center.py#L163C44-L163C53

if your comandline argument has ouptput unter a directory structure. thsi produces Directory not found Error.

Steps to reproduce:
python3 school_center.py sample_data/schools_grade12_2081.tsv sample_data/centers_grade12_2081.tsv sample_data/prefs.tsv -o sample_data/output_main.tsv
Traceback (most recent call last):
  File "/Users/user/Documents/MOEST/center-randomize/school_center.py", line 165, in <module>
    open(OUTPUT_DIR + args.output, 'w+', encoding='utf-8') as a_file:
FileNotFoundError: [Errno 2] No such file or directory: 'results/sample_data/output_main.tsv'

**Comment by nirmala-sharma** [comment]
Try to Run this : 
**python school_center.py sample_data/schools_grade12_2081.tsv sample_data/centers_grade12_2081.tsv sample_data/prefs.tsv**

Output Seems like this:
![Output](https://github.com/moest-np/center-randomize/assets/81033053/4aa3b532-5591-4f05-80d3-ae3573f73f06)
