### ISSUE TITLE
Interested to develop Mobile App

### ISSUE THREAD

**Issue by Ambikadulal** [moest-np/center-randomize#87]
### 🔖 Feature description

If we can provide full functionality in mobile applications, it would be great for the students and parents.

### Acknowledgements

- [X] My issue title is clear and descriptive.
- [X] I have checked existing issues to ensure this feature is not requested yet.
- [X] I have provided sufficient details for maintainers to understand and assess this request.

### Would you like to work on this issue?

Yes

**Comment by LuluW8071** [comment]
I'm not sure if mobile applications are within the scope, but once we have minimized bugs in the main code and streamlined the Streamlit web applications, we can consider developing them if aligns with the scope of the porject. 

>Once the Streamlit web apps have the essential features sorted out, we can then incorporate the necessary features for mobile applications.

**Comment by sumanashrestha** [comment]
mobile app is not particularly necessary for this app
